import 'package:flutter/material.dart';
import 'package:kopa_shop/constants/app_colors.dart';
import 'package:kopa_shop/constants/app_images.dart';
import 'package:kopa_shop/core/base_provider.dart';
import 'package:kopa_shop/models/shoes_card.dart';

class HomeProvider extends BaseProvider {
  List<ShoesCard> data = [
    ShoesCard(
      name: 'Nike 992K',
      foot: 'Розміри стопи:',
      width: '40',
      length: '28.5',
      lengthsm: 'Довжина / см',
      size: '10',
      widthsm: 'Ширина / см',
      materialle: 'Матеріал: Шкіра',
      eu: 'EU',
      image: 'assets/cross.png',
      color: AppColors.card,
    ),
    ShoesCard(
      name: 'Nike 992K',
      foot: 'Розміри стопи:',
      width: '40',
      length: '28.5',
      lengthsm: 'Довжина / см',
      size: '10',
      widthsm: 'Ширина / см',
      materialle: 'Матеріал: Шкіра',
      eu: 'EU',
      image: 'assets/cross.png',
      color: AppColors.card,
    ),
    ShoesCard(
      name: 'Nike 992K',
      foot: 'Розміри стопи:',
      width: '40',
      length: '28.5',
      lengthsm: 'Довжина / см',
      size: '10',
      widthsm: 'Ширина / см',
      materialle: 'Матеріал: Шкіра',
      eu: 'EU',
      image: 'assets/cross.png',
      color: AppColors.card,
    ),
    ShoesCard(
      name: 'Nike 992K',
      foot: 'Розміри стопи:',
      width: '40',
      length: '28.5',
      lengthsm: 'Довжина / см',
      size: '10',
      widthsm: 'Ширина / см',
      materialle: 'Матеріал: Шкіра',
      eu: 'EU',
      image: 'assets/cross.png',
      color: AppColors.card,
    ),
    ShoesCard(
      name: 'Nike 992K',
      foot: 'Розміри стопи:',
      width: '40',
      length: '28.5',
      lengthsm: 'Довжина / см',
      size: '10',
      widthsm: 'Ширина / см',
      materialle: 'Матеріал: Шкіра',
      eu: 'EU',
      image: 'assets/cross.png',
      color: AppColors.card,
    ),
    ShoesCard(
      name: 'Nike 992K',
      foot: 'Розміри стопи:',
      width: '40',
      length: '28.5',
      lengthsm: 'Довжина / см',
      size: '10',
      widthsm: 'Ширина / см',
      materialle: 'Матеріал: Шкіра',
      eu: 'EU',
      image: 'assets/cross.png',
      color: AppColors.card,
    ),
    ShoesCard(
      name: 'Nike 992K',
      foot: 'Розміри стопи:',
      width: '40',
      length: '28.5',
      lengthsm: 'Довжина / см',
      size: '10',
      widthsm: 'Ширина / см',
      materialle: 'Матеріал: Шкіра',
      eu: 'EU',
      image: 'assets/cross.png',
      color: AppColors.card,
    ),
  ];
}
