class AppStrings {
  static const String btnIn = "Вхiд";
  static const String name = "Ім'я";
  static const String validator = "Будь ласка, введіть ім'я";
  static const String surname = "Прізвище";
  static const String validatorsur = "Будь ласка, введіть прізвище";
  static const String city = "Місто";
  static const String validatorcity = "Будь ласка, введіть місто";
  static const String done = "Готово";
  static const String nike = "Nike 992K";
  static const String foot = "Розміри стопи:";
  static const String width = "40";
  static const String length = "28.5";
  static const String lengthsm = "Довжина / см";
  static const String size = "10";
  static const String widthsm = "Ширина / см";
  static const String materialle = "Матеріал: Шкіра";
  static const String phone = "+ 380";
  static const String validatorph = "Будь ласка, введіть номер";
  static const String verify = "Верифікувати";
  static const String exit = "Вийти";
  static const String eu = "EU";
  static const String description =
      "Опис про товар і як довго носив кросівки чи специфічні деталі взуття. натирало чи ні. чи дуло задувало. на широку ногу чи сайз не відповідає зязвленому. хвалиш взуття щоб точно купили. бо подарували дві пари, а ти за літо ще ні одної не зносив.";
  static const String seller = "Продавець";
  static const String situ = "Ukraine, Vinnytsia";
  static const String save = "Зберегти";
  static const String sizest = "Розмір";
  static const String material = "Матеріал";
  static const String price = "Ціна";
  static const String addphoto = "Додати фото";
  static const String model = "Модель";
  static const String opus = "Опис";
  static const String download = "СКИНУТИ";
  static const String sustained = "ЗАСТОСУВАТИ";
  static const String contact = "Контактний номер";
  static const String photo = "Додайте хоча б одне фото";
  static const String correct = "Введіть коректну ціну";
}
